In [1]:
import numpy as np


creamos un array gracias a python sencillo, pero no es de numpy 

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

nunmpy nos proporciona funciones para crear objetos arrays de numpy de manera sencilla

### arrays de numpy


In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

ahora creamos un arrays de datos de donde decimos de donde queremos que inicie, que valor quiero que termine y cuantos datos quiero generar

In [4]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

para las personas que trabajan con algebra lineal 

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

valores aleatorio y con dimensiones 

In [13]:
np.random.rand()

0.6819069236131827

In [14]:
np.random.rand(4)

array([0.21705162, 0.02066272, 0.25872043, 0.6607319 ])

In [15]:
np.random.rand(4,3)

array([[0.17652233, 0.49751881, 0.07926315],
       [0.72107865, 0.07427419, 0.63139527],
       [0.0671577 , 0.6340774 , 0.09078642],
       [0.33062897, 0.98323682, 0.90915145]])

In [25]:
np.random.randint(1,15)

12

y ahora con matriz o hasta tensor

In [3]:
np.random.randint(1,100,(10,10))

array([[52, 62, 65,  6,  5, 75, 22, 99, 30, 27],
       [18, 45, 35, 73, 85, 34, 74, 58, 48, 67],
       [ 3, 49, 82, 14, 41, 54, 52, 91, 25, 63],
       [73, 57, 76, 98, 50, 25, 83, 19, 54, 70],
       [84, 89,  7, 33, 12,  8, 70, 25, 22, 56],
       [98, 37,  6, 43, 50, 60, 37, 36, 64, 84],
       [66, 85, 41, 62, 50,  9, 43, 31, 40, 97],
       [19, 82, 78, 96, 13, 51, 42, 65, 41, 70],
       [26, 93,  5, 47, 55, 35, 70, 63, 52, 20],
       [67, 80, 32, 89, 48, 30, 73,  5, 82, 33]])

todo de array