el array de numpy tendra Un unico tipo de dato que  es el que voy a trabajar y el que yo voy a agregar puede ser float 64 y asi tener la mejor optimizacion de numpy y trabajar con los diferentes tipos de datos

In [1]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [9]:
arr=np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float32')

In [12]:
arr

array([1, 2, 3, 4])

In [13]:
arr=arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [18]:
arr = np.array([1,2,3,4])
arr=arr.astype(np.bool_)
arr

array([ True,  True,  True,  True])

In [19]:
arr = np.array([1,2,3,4])
arr=arr.astype(np.string_)
arr

array([b'1', b'2', b'3', b'4'], dtype='|S11')

In [20]:
arr = np.array(['1','2','3','4'])
arr=arr.astype(np.int8)
arr

array([1, 2, 3, 4], dtype=int8)