In [1]:
import numpy as np

## dimensiones

In [2]:
scalar= np.array(42)
print(scalar)
scalar.ndim

42


0

In [6]:
vector=np.array([1,2,3,4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [12]:
matriz=np.array([(1,2,3,4),(5,6,7,8)])
print(matriz)
matriz.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [13]:
tensor=np.array([[(1,2,3,4),(5,6,7,8)]])
print(tensor)
tensor.ndim

[[[1 2 3 4]
  [5 6 7 8]]]


3

## Agregar o eliminar dimensiones

In [4]:
vector=np.array([1,2,3,4],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3 4]]]]]]]]]]


10

In [2]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [5]:
print(vector,vector.ndim)
vector_2=np.squeeze(vector)
print(vector_2,vector_2.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]] 10
[1 2 3 4] 1


[[[[[1 2 3 4]]]]]


np.squeeeze comprime al numero de dimensiones que se cree que no se estan usando

In [13]:
pedro=np.array([1,2,3,4],ndmin=5)
print(pedro)
pedro.ndim

[[[[[1 2 3 4]]]]]


5

In [17]:
pedro= np.expand_dims(pedro,axis=0)
print(pedro)
pedro.ndim

[[[[[[1 2 3 4]]]]]]


6

In [18]:
print(pedro,pedro.ndim)
pedro2=np.squeeze(pedro)
print(pedro2,pedro2.ndim)

[[[[[[1 2 3 4]]]]]] 6
[1 2 3 4] 1
