In [3]:
import numpy as np

In [6]:
arr = np.random.randint(1,20,10)

In [8]:
matriz=arr.reshape(2,5)
matriz

array([[ 9, 16,  8, 15, 19],
       [12,  4, 16,  6, 15]])

In [9]:
arr

array([ 9, 16,  8, 15, 19, 12,  4, 16,  6, 15])

In [10]:
arr.max()

19

In [11]:
matriz

array([[ 9, 16,  8, 15, 19],
       [12,  4, 16,  6, 15]])

In [13]:
matriz.max()

19

In [14]:
matriz.max(0)

array([12, 16, 16, 15, 19])

In [16]:
matriz.max(1)

array([19, 16])

este te muestra el indice del mayor

In [17]:
arr.argmax()

4

ahora con matriz

In [25]:
matriz.argmax()

4

In [ ]:
matriz.argmax(0)

In [ ]:
matriz.argmax(1)

In [26]:
arr

array([ 9, 16,  8, 15, 19, 12,  4, 16,  6, 15])

In [27]:
matriz

array([[ 9, 16,  8, 15, 19],
       [12,  4, 16,  6, 15]])

In [23]:
arr.min()

4

In [24]:
matriz.min(0)

array([ 9,  4,  8,  6, 15])

In [28]:
arr.argmin()

6

In [32]:
matriz.argmin(0)

array([0, 1, 0, 1, 1], dtype=int64)

In [33]:
matriz.argmin(1)

array([2, 1], dtype=int64)

In [34]:
arr

array([ 9, 16,  8, 15, 19, 12,  4, 16,  6, 15])

In [35]:
arr.ptp()

15

In [37]:
matriz.ptp(0)

array([ 3, 12,  8,  9,  4])

In [36]:
matriz.ptp(1)

array([11, 12])

In [42]:
arr

array([ 9, 16,  8, 15, 19, 12,  4, 16,  6, 15])

In [45]:
arr.sort()
arr

array([ 4,  6,  8,  9, 12, 15, 15, 16, 16, 19])

In [54]:
matriz.sort()
matriz

array([[ 4,  6,  8,  9, 12],
       [15, 15, 16, 16, 19]])

In [49]:
np.percentile(arr,50)

13.5

In [47]:
np.median(arr)

13.5

In [55]:
np.median(matriz,1)

array([ 8., 16.])

In [56]:
np.std(arr)

4.732863826479693

In [58]:
np.std(arr) **2

22.4

In [57]:
np.var(arr)

22.4

media

In [59]:
np.mean(arr)

12.0

In [60]:
np.mean(matriz,1)

array([ 7.8, 16.2])

In [21]:
a=np.array([[1,2],[3,4]])
b=np.array([5,6])

In [ ]:
np.concatenate((a,b),axis=0)

: 

In [68]:
a.shape

(2, 2)

In [69]:
b.shape

(2,)

In [5]:
a.ndim

2

In [6]:
b.ndim

1

In [22]:
b=np.expand_dims(b,axis=0)

In [8]:
b.ndim

2

In [23]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

ahora si queremos con el eje 1, lo podemos hacer tambien , pero hay otra
forma que es con la transpuesta

In [18]:
np.concatenate((a, b),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

el error es que b esta 5,6 y y no 5,
                                  6 columnar y podemos usar el reshape o la
                                  tramspuesta

In [12]:
b

array([[5, 6]])

¿Qué es la transpuesta de una matriz?
En matemáticas, la matriz traspuesta es aquella que surge como resultado de realizar un cambio de columnas por filas y filas por columnas en la matriz original, generándose una nueva matriz (a la que llamamos traspuesta).

In [26]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])