In [1]:
import numpy as np

In [2]:
lista=[1,2]
lista

[1, 2]

In [3]:
lista*2

[1, 2, 1, 2]

con un arry de python lo que hace el operador es duplicarlo y no multiplicar cada uno de los elementos pero con un objeto array podemos hacerlo y con mas operadores

In [14]:
arr=np.arange(0,10)
arr2=arr.copy()

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
1/arr

C:\Users\Oniichans\AppData\Local\Temp\ipykernel_11632\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [16]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [17]:
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr*arr2

In [19]:
matriz=arr.reshape(2,5)
matriz2=matriz.copy()

In [20]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
matriz-matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [23]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [25]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])