In [3]:
import numpy as np


In [4]:
lista =[1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr=np.array(lista)
type(arr)


numpy.ndarray

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
matriz= [[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[0]

1

In [15]:
arr[0] + arr[5]

7

In [7]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

especificamos en la matriz la fila y la columna

In [8]:
matriz[0,1]


2

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [11]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[::3]

array([1, 4, 7])

In [14]:
arr[-1:]

array([9])

In [15]:
arr[-3:]

array([7, 8, 9])

In [16]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:,0:2]

trabajar con estos objetos array hacen que no consuman tanto espacio ,50% de rapidez y es sencillo acceder a estos .