### shape and heshape

In [1]:
import numpy as np


In [2]:
arr=np.random.randint(1,10,(3,2))

In [3]:
arr

array([[6, 2],
       [4, 8],
       [3, 1]])

saber cuantas columnas y filas tiene 

In [5]:
arr.shape

(3, 2)

In [6]:
arr

array([[1, 6],
       [2, 3],
       [7, 8]])

cambiar forma ,porque aveces tenes que trabajar con formas especificas en las redes neuronales o por una  api que entre de una forma y la tengamos que cambiar

In [13]:
arr.reshape(2,3)

array([[1, 6, 2],
       [3, 7, 8]])

In [14]:
np.reshape(arr,(1,6))

array([[1, 6, 2, 3, 7, 8]])

ahora apilamos los valores como lo hace el lenguaje C,fortran,o automatico.
c los apila por columnas y fortran por filas o como mejor este optimizado el almasenamiento en el sistema y lo hace de forma automatica 

In [17]:
arr

array([[1, 6],
       [2, 3],
       [7, 8]])

In [15]:
np.reshape(arr,(2,3),'C')

array([[1, 6, 2],
       [3, 7, 8]])

In [4]:
np.reshape(arr,(2,3),'F')

array([[8, 5, 2],
       [2, 7, 3]])